<a href="https://colab.research.google.com/github/HarikaTumula/Neural_assignment3/blob/main/icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
class Employee:

 print(Employee)

<class '__main__.Employee'>


In [25]:
class Employee:
  empcount = 0

  def __init__(self, name, age, id, dept):
    self.name = name
    self.age = age
    self.id = id
    self.dept = dept 

    Employee.empcount += 1

E1 = Employee("Harika", 28, 2535, 'HR')
E2 = Employee("Vinith", 30, 2536, 'IT')
E3 = Employee("Spandana", 28, 2537, 'Engineer')
E4 = Employee('Sweety', 27, 2538, 'IT')

print("Total count of employees is ",Employee.empcount)

Total count of employees is  4


In [100]:
class Employee:
  def __init__(self, name, family, salary, dept):
    self.name = name
    self.family = family
    self.salary = salary
    self.dept = dept

  def display(self):
      print('Employee:',self.name,'Family:', self.family, 'Salary:', self.salary, 'Department:', self.dept)
 
E1 = Employee("Harika", 'Small', 25350, 'HR')
E1.display()

E2 = Employee("Vinith", 'Small', 24350, 'IT')
E2.display()

E3 = Employee("Spandana", 'Joint', 26350, 'HR')
E3.display()

Employee: Harika Family: Small Salary: 25350 Department: HR
Employee: Vinith Family: Small Salary: 24350 Department: IT
Employee: Spandana Family: Joint Salary: 26350 Department: HR


In [90]:
class Employee:
  def __init__(self, name, family, salary, dept):
    self.name = name
    self.family = family
    self.salary = salary
    self.dept = dept

  def solve(salary):
   salary.remove(min(salary))
   salary.remove(max(salary))
   return sum(salary)/len(salary)

salary = [80000,60000,20000,80500,20500,45000]
print(solve(salary))


51375.0


In [98]:
class Employee:
  def __init__(self, name, age, id, dept):
    self.name = name
    self.age = age
    self.id = id
    self.dept = dept

E1 = Employee("Harika", 28, 2535, 'HR')
E2 = Employee("Vinith", 30, 2536, 'IT')
E3 = Employee("Spandana", 28, 2537, 'Engineer')

print("Employee1:", E1.name)
print('age:', E1.age)
print('id:', E1.id)
print('dept:', E1.dept)
print('Employee2:', E2.name)
print('age:', E2.age)
print('id:', E2.id)
print('dept:', E2.dept)
print('Employee3:', E3.name)
print('age:', E3.age)
print('id:', E3.id)
print('dept:', E3.dept)

class Fulltime_emp(Employee):
   def display(self):
       print("fulltime_employee " + self.name)

emp = Fulltime_emp("Singedi Reddy", 30, 2564, 'Sr.Engineer')

print(emp.name)
emp.display()

Employee1: Harika
age: 28
id: 2535
dept: HR
Employee2: Vinith
age: 30
id: 2536
dept: IT
Employee3: Spandana
age: 28
id: 2537
dept: Engineer
Singedi Reddy
fulltime_employee Singedi Reddy


In [111]:
class Employee:
  def __init__(self):
        self._database = []

  def add_employee(self, name, age, salary, dept):
        self._database.append((name, age, salary, dept))

new_emp = Employee()

def add_employee_input(database):
      database.add_employee(
        input('Enter name:'),
        input('Enter age:'),
        input('Enter salary:'),
        input('Enter dept:'),
    )
  
add_employee_input(new_emp)

Enter name:Harika
Enter age:28
Enter salary:25000
Enter dept:hr


In [259]:
import numpy as np
x = np.random.randint(20,size=(20))
x

array([11, 12, 18,  9, 18,  9, 13,  9,  7,  1,  6, 10, 11, 18, 15, 14,  0,
        2, 19, 15])

In [272]:
x=x.reshape(4,5)
x

array([[11, 12, 18,  9, 18],
       [ 9, 13,  9,  7,  1],
       [ 6, 10, 11, 18, 15],
       [14,  0,  2,  0, 15]])

In [276]:
np.amax(x)           # Maximum of the flattened array
np.amax(x, axis=1)


array([18, 13, 18, 15])

In [279]:
np.amax(x)           
x[x==np.amax(x, axis=1)]=0
x

<ipython-input-279-e37e3f0de9a9>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  x[x==np.amax(x, axis=1)]=0


array([[11, 12, 18,  9, 18],
       [ 9, 13,  9,  7,  1],
       [ 6, 10, 11, 18, 15],
       [14,  0,  2,  0, 15]])